### ISSUE TITLE
Block on isGameOver in battleship

### ISSUE THREAD

**Issue by joshlw04** [joshlw04/battleship#1]
I know it is past 9pm, but I fell asleep when I got home so I figured I could work a little later...

 I spent the night working on trying to understand how to dig into the Cell class from the Board class, to access the properties I needed to make the isGameOver method work. Right now, I'm stuck on the syntax and probably the logic of that function. I know if you use return inside a for loop, the loop will end, so I tried assigning a the boolean to a variable. I could access the function in the console, but it would only return false. I'm unsure if this is the correct way to 'return' true or false.

**Comment by amadden80** [comment]
Great point!   Let's say we were looking to see if there are any 3's in an array:

``` js
function hasAThree(){
  for (let i = 0; i < numbers.length; i++ ){
      if (numbers[i] === 3) {
        return true
      }
  }
  return false;
}

const numbers = [2, 4, 5, 3, 2];
const numbersHasThree = hasAThree(numbers);
```

Take a good look at that above.  It's not the exact code you'd use in your project, but it demo's the idea you came up with, i.e. returning something gin a loop to break from a function.  

How does this code feel?  Want to talk through this function together?

**Comment by joshlw04** [comment]
that function makes total sense. In this game, we need to loop through every cell to see if ALL of them with ships have been played && exploded. By using return inside the loop, it will end as soon as it finds the first cell that matches that conditional statement, right? SO, I feel that assigning a variable to return T/F after going through the whole array is making more sense to me. I got it to work in the console, so I feel good about it. 

```
 isGameOver() {
    let gameOver;
    for (let i = 0; i < this.cellsInBoard.length; i++) { 
      if (this.cellsInBoard[i].hasBoat === true) {
        if (this.cellsInBoard[i].beenPlayed && this.cellsInBoard[i].isExplosion) { 
          gameOver = true;
        }
      } else {
        gameOver = false;
      }
    }
    return gameOver;
  }
```
